In [277]:
import pandas as pand
import sympy as sp

Número de alternativas = 4 
Alternativas =


Colombia Yappo          a1 

PCHogar                 a2

Medmall                 a3

eBay                    a4
  
Número de criterios = 10

Criterios = 


Eficiencia              c1      excelente   

prácticidad             c2      bueno       

fácilidad de uso        c3      malo        

ahorro de tiempo        c4      excelente   

comunicación            c5      malo        

Confianza               c6      muy bueno   

Seguridad               c7      bueno       

Familiar                c8      inaceptable

Experiencia             c9      muy malo    

Competencia             c10     muy bueno

In [278]:
crit = ['Eficiencia', 'prácticidad', 'fácilidad de uso', 
        'ahorro de tiempo', 'comunicación', 'Confianza', 
        'Seguridad', 'Familiar', 'Experiencia', 'Competencia']
alt = ['Colombia Yappo', 'PCHogar', 'MedMall', 'eBay', '']
alt.append('pesos')

alt1 = []
for i in range(0,4,1):
        alt1.append('A'+str(i+1))
alt1.append('')
alt1.append('W')
crit1 = []
for i in range(0,10,1):
        crit1.append('C'+str(i+1))

Escala de valores lingüistícos=


inaceptable     :   [1.1.2]

muy malo        :   [1,2,3]       

malo            :   [2,3,4]

medio           :   [4,5,6]

bueno           :   [6,7,8]

muy bueno       :   [7,8,9]

excelente       :   [8,9,9]

In [279]:
ColYa = ['bueno', 'malo', 'excelente', 'muy malo', 'muy bueno', 'muy bueno', 'medio', 'inaceptable', 'bueno', 'excelente']
PCH = ['medio', 'malo', 'excelente', 'excelente', 'inaceptable', 'muy bueno', 'medio', 'bueno', 'muy malo', 'muy bueno']
MMall = ['excelente', 'muy malo', 'muy malo', 'muy malo', 'muy bueno', 'medio', 'inaceptable', 'excelente', 'medio', 'bueno']
ebay = ['muy bueno', 'bueno', 'muy bueno', 'excelente', 'inaceptable', 'medio', 'excelente', 'bueno', 'malo', 'muy bueno']
sep = ['-','-','-','-','-','-','-','-','-','-',]
Pesos = ['excelente', 'bueno', 'malo', 'excelente', 'malo', 'muy bueno', 'bueno', 'inaceptable', 'muy malo', 'muy bueno']

In [280]:

MTfuzzy = [ColYa, PCH, MMall, ebay, sep, Pesos]
MTfuzzyFrame = pand.DataFrame(MTfuzzy, index= alt1, columns= crit1)  
display(MTfuzzyFrame)
#print(MTfuzzyFrame.to_latex())

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10
A1,bueno,malo,excelente,muy malo,muy bueno,muy bueno,medio,inaceptable,bueno,excelente
A2,medio,malo,excelente,excelente,inaceptable,muy bueno,medio,bueno,muy malo,muy bueno
A3,excelente,muy malo,muy malo,muy malo,muy bueno,medio,inaceptable,excelente,medio,bueno
A4,muy bueno,bueno,muy bueno,excelente,inaceptable,medio,excelente,bueno,malo,muy bueno
,-,-,-,-,-,-,-,-,-,-
W,excelente,medio,medio,medio,muy malo,muy bueno,excelente,inaceptable,bueno,malo

In [281]:
I = sp.Matrix([1,1,2])
MM = sp.Matrix([1,2,3])       
M = sp.Matrix([2,3,4])
H = sp.Matrix([4,5,6])
B = sp.Matrix([6,7,8])
MB = sp.Matrix([7,8,9])
E = sp.Matrix([8,9,9])

NTfuzzy = MTfuzzy
for i in range(0,6,1):
    for j in range(0,10,1):
        if MTfuzzy[i][j] == 'inaceptable':
            NTfuzzy[i][j] = I.T
        elif MTfuzzy[i][j] == 'muy malo':
            NTfuzzy[i][j] = MM.T
        elif MTfuzzy[i][j] == 'malo':
            NTfuzzy[i][j] = M.T
        elif MTfuzzy[i][j] == 'medio':
            NTfuzzy[i][j] = H.T
        elif MTfuzzy[i][j] == 'bueno':
            NTfuzzy[i][j] = B.T
        elif MTfuzzy[i][j] == 'muy bueno':
            NTfuzzy[i][j] = MB.T
        elif MTfuzzy[i][j] == 'excelente':
            NTfuzzy[i][j] = E.T
NTfuzzyFrame = pand.DataFrame(NTfuzzy, index= alt1, columns= crit1)  
display(NTfuzzyFrame)
#print(NTfuzzyFrame.to_latex())
#IFrame = pand.DataFrame(I.tolist())
#MMFrame = pand.DataFrame(MM.tolist())
#MFrame = pand.DataFrame(M.tolist())
#HFrame = pand.DataFrame(H.tolist())
#BFrame = pand.DataFrame(B.tolist())
#MBFrame = pand.DataFrame(MB.tolist())
#EFrame = pand.DataFrame(E.tolist())
#print(IFrame.to_latex())
#print(MBFrame.to_latex())
#print(BFrame.to_latex())
#print(HFrame.to_latex())
#print(BFrame.to_latex())
#print(MBFrame.to_latex())
#print(EFrame.to_latex())

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10
A1,"[6, 7, 8]","[2, 3, 4]","[8, 9, 9]","[1, 2, 3]","[7, 8, 9]","[7, 8, 9]","[4, 5, 6]","[1, 1, 2]","[6, 7, 8]","[8, 9, 9]"
A2,"[4, 5, 6]","[2, 3, 4]","[8, 9, 9]","[8, 9, 9]","[1, 1, 2]","[7, 8, 9]","[4, 5, 6]","[6, 7, 8]","[1, 2, 3]","[7, 8, 9]"
A3,"[8, 9, 9]","[1, 2, 3]","[1, 2, 3]","[1, 2, 3]","[7, 8, 9]","[4, 5, 6]","[1, 1, 2]","[8, 9, 9]","[4, 5, 6]","[6, 7, 8]"
A4,"[7, 8, 9]","[6, 7, 8]","[7, 8, 9]","[8, 9, 9]","[1, 1, 2]","[4, 5, 6]","[8, 9, 9]","[6, 7, 8]","[2, 3, 4]","[7, 8, 9]"
,-,-,-,-,-,-,-,-,-,-
W,"[8, 9, 9]","[4, 5, 6]","[4, 5, 6]","[4, 5, 6]","[1, 2, 3]","[7, 8, 9]","[8, 9, 9]","[1, 1, 2]","[6, 7, 8]","[2, 3, 4]"

In [282]:
c = []
NormFuzzy = NTfuzzy
for i in range(0,10,1):
    c = []
    for j in range(0,4,1):
        c.append(NTfuzzy[j][i][0,2])
    c = max(c) 
    for k in range(0,4,1):
        NormFuzzy[k][i] = NTfuzzy[k][i]/c
NormFuzzyFrame = pand.DataFrame(NormFuzzy, index= alt1, columns= crit1)  
display(NormFuzzyFrame)
#print(NormFuzzyFrame.to_latex())

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10
A1,"[2/3, 7/9, 8/9]","[1/4, 3/8, 1/2]","[8/9, 1, 1]","[1/9, 2/9, 1/3]","[7/9, 8/9, 1]","[7/9, 8/9, 1]","[4/9, 5/9, 2/3]","[1/9, 1/9, 2/9]","[3/4, 7/8, 1]","[8/9, 1, 1]"
A2,"[4/9, 5/9, 2/3]","[1/4, 3/8, 1/2]","[8/9, 1, 1]","[8/9, 1, 1]","[1/9, 1/9, 2/9]","[7/9, 8/9, 1]","[4/9, 5/9, 2/3]","[2/3, 7/9, 8/9]","[1/8, 1/4, 3/8]","[7/9, 8/9, 1]"
A3,"[8/9, 1, 1]","[1/8, 1/4, 3/8]","[1/9, 2/9, 1/3]","[1/9, 2/9, 1/3]","[7/9, 8/9, 1]","[4/9, 5/9, 2/3]","[1/9, 1/9, 2/9]","[8/9, 1, 1]","[1/2, 5/8, 3/4]","[2/3, 7/9, 8/9]"
A4,"[7/9, 8/9, 1]","[3/4, 7/8, 1]","[7/9, 8/9, 1]","[8/9, 1, 1]","[1/9, 1/9, 2/9]","[4/9, 5/9, 2/3]","[8/9, 1, 1]","[2/3, 7/9, 8/9]","[1/4, 3/8, 1/2]","[7/9, 8/9, 1]"
,-,-,-,-,-,-,-,-,-,-
W,"[8, 9, 9]","[4, 5, 6]","[4, 5, 6]","[4, 5, 6]","[1, 2, 3]","[7, 8, 9]","[8, 9, 9]","[1, 1, 2]","[6, 7, 8]","[2, 3, 4]"

In [283]:
PondFuzzy = NormFuzzy
for i in range(0,10,1):
    for j in range(0,4,1):
        for k in range(0,3,1):
            PondFuzzy[j][i][0,k] = NormFuzzy[j][i][0,k] * NormFuzzy[5][i][0,k]

PondFuzzyFrame = pand.DataFrame(PondFuzzy, index= alt1, columns= crit1)  
display(PondFuzzyFrame)
#print(PondFuzzyFrame.to_latex())

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10
A1,"[16/3, 7, 8]","[1, 15/8, 3]","[32/9, 5, 6]","[4/9, 10/9, 2]","[7/9, 16/9, 3]","[49/9, 64/9, 9]","[32/9, 5, 6]","[1/9, 1/9, 4/9]","[9/2, 49/8, 8]","[16/9, 3, 4]"
A2,"[32/9, 5, 6]","[1, 15/8, 3]","[32/9, 5, 6]","[32/9, 5, 6]","[1/9, 2/9, 2/3]","[49/9, 64/9, 9]","[32/9, 5, 6]","[2/3, 7/9, 16/9]","[3/4, 7/4, 3]","[14/9, 8/3, 4]"
A3,"[64/9, 9, 9]","[1/2, 5/4, 9/4]","[4/9, 10/9, 2]","[4/9, 10/9, 2]","[7/9, 16/9, 3]","[28/9, 40/9, 6]","[8/9, 1, 2]","[8/9, 1, 2]","[3, 35/8, 6]","[4/3, 7/3, 32/9]"
A4,"[56/9, 8, 9]","[3, 35/8, 6]","[28/9, 40/9, 6]","[32/9, 5, 6]","[1/9, 2/9, 2/3]","[28/9, 40/9, 6]","[64/9, 9, 9]","[2/3, 7/9, 16/9]","[3/2, 21/8, 4]","[14/9, 8/3, 4]"
,-,-,-,-,-,-,-,-,-,-
W,"[8, 9, 9]","[4, 5, 6]","[4, 5, 6]","[4, 5, 6]","[1, 2, 3]","[7, 8, 9]","[8, 9, 9]","[1, 1, 2]","[6, 7, 8]","[2, 3, 4]"

In [284]:
A = [[],[]]
for i in range(0,10,1):
    c = []
    ind = 0
    for j in range(0,4,1):
        c.append(PondFuzzy[j][i][0,2])
    c = max(c)
    cont = []
    for j in range(0,4,1):
        if c == PondFuzzy[j][i][0,2]:
            cont.append(j)
    if len(cont) > 1:
        c = []
        for k in cont:
            c.append(PondFuzzy[k][i][0,1])
        c = max(c)
        cont = []
        for j in range(0,4,1):
            if c == PondFuzzy[j][i][0,1]:
                cont.append(j)
        if len(cont) > 1:
            c = []
            for k in cont:
                c.append(PondFuzzy[k][i][0,0])
            c = max(c)
            for k in cont:
                if PondFuzzy[k][i][0,0] == c:
                    ind = k
        elif len(cont) == 1:
            ind = cont[0]
    elif len(cont) == 1:
        ind = cont[0]
    A[0].append(PondFuzzy[ind][i])
for i in range(0,10,1):
    c = []
    ind = 0
    for j in range(0,4,1):
        c.append(PondFuzzy[j][i][0,0])
    c = min(c)
    cont = []
    for j in range(0,4,1):
        if c == PondFuzzy[j][i][0,0]:
            cont.append(j)
    if len(cont) > 1:
        c = []
        for k in cont:
            c.append(PondFuzzy[k][i][0,1])
        c = min(c)
        cont = []
        for j in range(0,4,1):
            if c == PondFuzzy[j][i][0,1]:
                cont.append(j)
        if len(cont) > 1:
            c = []
            for k in cont:
                c.append(PondFuzzy[k][i][0,2])
            c = min(c)
            for k in cont:
                if PondFuzzy[k][i][0,2] == c:
                    ind = k
        elif len(cont) == 1:
            ind = cont[0]
    elif len(cont) == 1:
        ind = cont[0]
    A[1].append(PondFuzzy[ind][i])
id = ['ideal', 'no ideal']
AFrame = pand.DataFrame(A, index = id, columns = crit1)
display(AFrame)
#print(AFrame.to_latex())

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10
ideal,"[64/9, 9, 9]","[3, 35/8, 6]","[32/9, 5, 6]","[32/9, 5, 6]","[7/9, 16/9, 3]","[49/9, 64/9, 9]","[64/9, 9, 9]","[8/9, 1, 2]","[9/2, 49/8, 8]","[16/9, 3, 4]"
no ideal,"[32/9, 5, 6]","[1/2, 5/4, 9/4]","[4/9, 10/9, 2]","[4/9, 10/9, 2]","[1/9, 2/9, 2/3]","[28/9, 40/9, 6]","[8/9, 1, 2]","[1/9, 1/9, 4/9]","[3/4, 7/4, 3]","[4/3, 7/3, 32/9]"

In [285]:
Dideal = sp.zeros(4,10)
Dnoideal = sp.zeros(4,10)
for i in range(0,10,1):
    for j in range(0,4,1):
        di = 0
        dn = 0
        for k in range(0,3):
            di = di + (PondFuzzy[j][i][0,k] - A[0][i][0,k])**2
            dn = dn + (PondFuzzy[j][i][0,k] - A[1][i][0,k])**2
        Dideal[j,i] = di**(1/2)
        Dnoideal[j,i] = dn**(1/2)
alt.pop(5)
alt.pop(4)
DidealList = Dideal.tolist()
DnoidealList = Dnoideal.tolist()
DidealFrame = pand.DataFrame(DidealList, index = alt, columns = crit)
DnoidealFrame = pand.DataFrame(DnoidealList, index = alt, columns = crit)
display(DidealFrame)
display(DnoidealFrame)

,Eficiencia,prácticidad,fácilidad de uso,ahorro de tiempo,comunicación,Confianza,Seguridad,Familiar,Experiencia,Competencia
Colombia Yappo,2.85665780715165,4.38748219369606,0,6.38768104524658,0,0,6.13530564101268,1.95315509236077,0,0
PCHogar,6.13530564101268,4.38748219369606,0,0,2.88247150468285,0,6.13530564101268,0.384900179459751,7.62909725983356,0.400616808384888
MedMall,0,5.48435274212008,6.38768104524658,6.38768104524658,0,4.64279609239471,12.3173069046247,0,3.05163890393343,0.916245694581702
eBay,1.33795495319914,0,0.711458248603650,0,2.88247150468285,4.64279609239471,0,0.384900179459751,6.10327780786685,0.400616808384888

,Eficiencia,prácticidad,fácilidad de uso,ahorro de tiempo,comunicación,Confianza,Seguridad,Familiar,Experiencia,Competencia
Colombia Yappo,3.34073252852731,1.09687054842402,6.38768104524658,0,2.88247150468285,4.64279609239471,6.25388767976457,0,7.62909725983356,0.916245694581702
PCHogar,0,1.09687054842402,6.38768104524658,6.38768104524658,0,4.64279609239471,6.25388767976457,1.59086900703071,0,0.598351645237167
MedMall,6.13530564101268,0,0,0,2.88247150468285,0,0,1.95315509236077,4.57745835590014,0
eBay,5.01109879279097,5.48435274212008,5.84997625826141,6.38768104524658,0,0,12.3173069046247,1.59086900703071,1.52581945196671,0.598351645237167

In [286]:
Dalt = sp.zeros(4,2)
for i in range(0,4,1):
    dideal = 0
    dnoideal = 0
    for j in range(0,10,1):
        dideal = dideal + Dideal[i,j] 
        dnoideal = dnoideal + Dnoideal[i,j]
    Dalt[i,0] = dideal
    Dalt[i,1] = dnoideal
DaltList = Dalt.tolist()
DaltListFrame = pand.DataFrame(DaltList, index = alt, columns = id)
display(DaltListFrame)
#print(DaltListFrame.to_latex())

                           ideal          no ideal
Colombia Yappo  21.7202817794677  33.1497823534553
PCHogar         27.9551792280825  26.9581370633443
MedMall         39.1877024281478  15.5483905939564
eBay            16.4634755945918  38.7654558472784

In [287]:
CC = sp.zeros(4,1)
for i in range(0,4,1):
    CC[i,0] = Dalt[i,1]/(Dalt[i,1]+Dalt[i,0])

CCList = CC.tolist()
CCListFrame = pand.DataFrame(CCList, index = alt, columns = ['Coeficiente de Cercanía'])
CCListFrame = CCListFrame.sort_values(by = 'Coeficiente de Cercanía', ascending = False)
display(CCListFrame)
#print(CCListFrame.to_latex())

               Coeficiente de Cercanía
eBay                 0.701904868249713
Colombia Yappo       0.604150603380921
PCHogar              0.490921672263911
MedMall              0.284061023275401